language: scala
stages:
  - name: site
jobs:
  include:      
    - stage: site
      name: Make Microsite on 2.12.10
      install: gem install jekyll -v 4.0.0
      script: sbt ++2.12.10! microsite/publishMicrosite
      after_script: find /home/travis/build/timo-schmid/mittelalterfest/target/site
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier
