language: scala
stages:
  - name: site
jobs:
  include:      
    - stage: site
      name: Make Microsite on 2.12.10
      env: TEST="docs"
      install: gem install jekyll -v 4.0.0
      script: sbt ++2.12.10! docs/makeMicrosite
